# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8288839674cbebc95a0bfe4e19b0c457130d4c94aee4c656c2cb9e32f96e0730895d0bea4a21fc37acbe8c43c7baec49ee6782ae37dea4f64c2a729026255ff7

test:
  secret_key_base: 953b678bebf0b6e064fcb9f5690846b5d90c1ff22843878af329d5812b53746789869b744c2af9db8795e17e0124176896acd03ef9e704ad3b31058beb51042f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
